version: "3.3"

volumes:
  postgres_data: {}
  env: {}

services:
  redoc-ui:
    image: redocly/redoc
    restart: always
    environment:
      SPEC_URL: 'http://localhost:10000/swagger.yml'

    network_mode: "host"
    depends_on:
      - redoc-backend
    ports:
      - "127.0.0.1:80:80"

  redoc-backend:
    image: redocly/redoc
    restart: always
    environment:
      SPEC_URL: 'swagger.yml'

    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger.yml 


    ports:
      - "127.0.0.1:10000:80"